-- Basic
require("core.plugins")
require("core.mappings")
require("core.colors")
require("core.configs")
require("core.autocommands")

-- Plugins
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.nullls")
require("plugins.lspkind")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.toggleterm")
require("plugins.dashboard")
require("plugins.whichkey")
